<?php
/**
 * ### No soure file - only for documentation
 * 
 * #### Organization 
 *   - Airline 
 *   - Consortium 
 *   - Corporation 
 *   - EducationalOrganization 
 *     - CollegeOrUniversity 
 *     - ElementarySchool 
 *     - HighSchool 
 *     - MiddleSchool 
 *     - Preschool 
 *     - School 
 *   - FundingScheme 
 *   - GovernmentOrganization 
 *   - LibrarySystem 
 *   - LocalBusiness 
 *     - AnimalShelter 
 *     - ArchiveOrganization 
 *     - AutomotiveBusiness 
 *       - AutoBodyShop
 *       - AutoDealer
 *       - AutoPartsStore
 *       - AutoRental
 *       - AutoRepair
 *       - AutoWash
 *       - GasStation
 *       - MotorcycleDealer
 *       - MotorcycleRepair
 *     - ChildCare 
 *     - Dentist 
 *     - DryCleaningOrLaundry 
 *     - EmergencyService 
 *       - FireStation
 *       - Hospital
 *       - PoliceStation
 *     - EmploymentAgency 
 *     - EntertainmentBusiness 
 *       - AdultEntertainment
 *       - AmusementPark
 *       - ArtGallery
 *       - Casino
 *       - ComedyClub
 *       - MovieTheater
 *       - NightClub
 *     - FinancialService 
 *       - AccountingService
 *       - AutomatedTeller
 *       - BankOrCreditUnion
 *       - InsuranceAgency
 *     - FoodEstablishment 
 *       - Bakery
 *       - BarOrPub
 *       - Brewery
 *       - CafeOrCoffeeShop
 *       - Distillery
 *       - FastFoodRestaurant
 *       - IceCreamShop
 *       - Restaurant
 *       - Winery
 *     - GovernmentOffice 
 *       - PostOffice
 *     - HealthAndBeautyBusiness 
 *       - BeautySalon
 *       - DaySpa
 *       - HairSalon
 *       - HealthClub
 *       - NailSalon
 *       - TattooParlor
 *     - HomeAndConstructionBusiness 
 *       - Electrician
 *       - GeneralContractor
 *       - HVACBusiness
 *       - HousePainter
 *       - Locksmith
 *       - MovingCompany
 *       - Plumber
 *       - RoofingContractor
 *     - InternetCafe 
 *     - LegalService 
 *       - Attorney
 *       - Notary
 *     - Library 
 *     - LodgingBusiness 
 *       - BedAndBreakfast
 *       - Campground
 *       - Hostel
 *       - Hotel
 *       - Motel
 *       - Resort
 *     - MedicalBusiness 
 *       - *!!! subtypes of MedicalBusiness currently not supported by google*
 *         - *(CommunityHealth)*
 *         - *(Dentist)*
 *         - *(Dermatology)*
 *         - *(DietNutrition)*
 *         - *(Emergency)*
 *         - *(Geriatric)*
 *         - *(Gynecologic)*
 *         - *(MedicalClinic)*
 *           - *(CovidTestingFacility)*
 *         - *(Midwifery)*
 *         - *(Nursing)*
 *         - *(Obstetric)*
 *         - *(Oncologic)*
 *         - *(Optician)*
 *         - *(Optometric)*
 *         - *(Otolaryngologic)*
 *         - *(Pediatric)*
 *         - *(Pharmacy)*
 *         - *(Physician)*
 *         - *(Physiotherapy)*
 *         - *(PlasticSurgery)*
 *         - *(Podiatric)*
 *         - *(PrimaryCare)*
 *         - *(Psychiatric)*
 *         - *(PublicHealth)*
 *       - *!!!*
 *     - ProfessionalService 
 *     - RadioStation 
 *     - RealEstateAgent 
 *     - RecyclingCenter 
 *     - SelfStorage 
 *     - ShoppingCenter 
 *     - SportsActivityLocation 
 *       - BowlingAlley
 *       - ExerciseGym
 *       - GolfCourse
 *       - HealthClub
 *       - PublicSwimmingPool
 *       - SkiResort
 *       - SportsClub
 *       - StadiumOrArena
 *       - TennisComplex
 *     - Store 
 *       - AutoPartsStore
 *       - BikeStore
 *       - BookStore
 *       - ClothingStore
 *       - ComputerStore
 *       - ConvenienceStore
 *       - DepartmentStore
 *       - ElectronicsStore
 *       - Florist
 *       - FurnitureStore
 *       - GardenStore
 *       - GroceryStore
 *       - HardwareStore
 *       - HobbyShop
 *       - HomeGoodsStore
 *       - JewelryStore
 *       - LiquorStore
 *       - MensClothingStore
 *       - MobilePhoneStore
 *       - MovieRentalStore
 *       - MusicStore
 *       - OfficeEquipmentStore
 *       - OutletStore
 *       - PawnShop
 *       - PetStore
 *       - ShoeStore
 *       - SportingGoodsStore
 *       - TireShop
 *       - ToyStore
 *       - WholesaleStore
 *     - TelevisionStation 
 *     - TouristInformationCenter 
 *     - TravelAgency 
 *   - MedicalOrganization 
 *     - Dentist 
 *     - DiagnosticLab 
 *     - Hospital 
 *     - MedicalClinic 
 *     - Pharmacy 
 *     - Physician 
 *     - VeterinaryCare 
 *   - NGO 
 *   - NewsMediaOrganization 
 *   - PerformingGroup 
 *     - DanceGroup 
 *     - MusicGroup 
 *     - TheaterGroup 
 *   - Project 
 *     - FundingAgency 
 *     - ResearchProject 
 *   - SportsOrganization 
 *     - SportsTeam 
 *   - WorkersUnion 
 * 
 */
class DocJsonLDLocalBusinessType {}